/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';


export const getGetApiUserByUidResponseMock = (): string => (faker.word.sample())


export const getGetApiUserByUidMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/:uid', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {

  const resolvedBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiUserByUidResponseMock();
    const textBody = typeof resolvedBody === 'string' ? resolvedBody : JSON.stringify(resolvedBody ?? null);
    return HttpResponse.text(textBody,
      { status: 200
      })
  }, options)
}
export const getUserMock = () => [
  getGetApiUserByUidMockHandler()
]
