/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';



  type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get user Information via UID
 */
export const getGetApiUserByUidUrl = (uid: string,) => {




  return `/api/user/${uid}`
}

export const getApiUserByUid = async (uid: string, options?: RequestInit): Promise<string> => {

  const res = await fetch(getGetApiUserByUidUrl(uid),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: string = body ? JSON.parse(body) : {}
  return data
}




export const getGetApiUserByUidKey = (uid: string,) => [`/api/user/${uid}`] as const;

export type GetApiUserByUidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserByUid>>>

export const useGetApiUserByUid = <TError = Promise<unknown>>(
  uid: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiUserByUid>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(uid)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiUserByUidKey(uid) : null);
  const swrFn = () => getApiUserByUid(uid, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
