/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GetApiRoomByRid200
} from '../model';


export const getGetApiRoomByRidResponseMock = (overrideResponse: Partial<Extract<GetApiRoomByRid200, object>> = {}): GetApiRoomByRid200 => ({player: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.fromRegExp("^[a-zA-Z][a-zA-Z0-9_\\-]+$"))), ...overrideResponse})


export const getWebSocketByRidGidMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.get('*/api/room/:rid/game/:gid', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiRoomByRidMockHandler = (overrideResponse?: GetApiRoomByRid200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiRoomByRid200> | GetApiRoomByRid200), options?: RequestHandlerOptions) => {
  return http.get('*/api/room/:rid', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiRoomByRidResponseMock(),
      { status: 200
      })
  }, options)
}
export const getRoomMock = () => [
  getWebSocketByRidGidMockHandler(),
  getGetApiRoomByRidMockHandler()
]
