/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ErrorResponse,
  GetApiRoomByRid200
} from '../model';



  type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * WebSocket connected by RID and GID
 */
export const getWebSocketByRidGidUrl = (rid: string,
    gid: string,) => {




  return `/api/room/${rid}/game/${gid}`
}

export const webSocketByRidGid = async (rid: string,
    gid: string, options?: RequestInit): Promise<unknown> => {

  const res = await fetch(getWebSocketByRidGidUrl(rid,gid),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: unknown = body ? JSON.parse(body) : {}
  return data
}




export const getWebSocketByRidGidKey = (rid: string,
    gid: string,) => [`/api/room/${rid}/game/${gid}`] as const;

export type WebSocketByRidGidQueryResult = NonNullable<Awaited<ReturnType<typeof webSocketByRidGid>>>

export const useWebSocketByRidGid = <TError = Promise<void>>(
  rid: string,
    gid: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof webSocketByRidGid>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(rid && gid)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getWebSocketByRidGidKey(rid,gid) : null);
  const swrFn = () => webSocketByRidGid(rid,gid, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get room Information via RID
 */
export const getGetApiRoomByRidUrl = (rid: string,) => {




  return `/api/room/${rid}`
}

export const getApiRoomByRid = async (rid: string, options?: RequestInit): Promise<GetApiRoomByRid200> => {

  const res = await fetch(getGetApiRoomByRidUrl(rid),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetApiRoomByRid200 = body ? JSON.parse(body) : {}
  return data
}




export const getGetApiRoomByRidKey = (rid: string,) => [`/api/room/${rid}`] as const;

export type GetApiRoomByRidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiRoomByRid>>>

export const useGetApiRoomByRid = <TError = Promise<ErrorResponse>>(
  rid: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiRoomByRid>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(rid)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiRoomByRidKey(rid) : null);
  const swrFn = () => getApiRoomByRid(rid, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
