/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiUserByUid200DataHistoryItemPlayers } from './getApiUserByUid200DataHistoryItemPlayers';
import type { GetApiUserByUid200DataHistoryItemStepsItem } from './getApiUserByUid200DataHistoryItemStepsItem';

export type GetApiUserByUid200DataHistoryItem = {
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  gid: string;
  players: GetApiUserByUid200DataHistoryItemPlayers;
  status: 'playing' | 'finished';
  steps: GetApiUserByUid200DataHistoryItemStepsItem[];
};
