/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiGameByGid200DataPlayers } from './getApiGameByGid200DataPlayers';
import type { GetApiGameByGid200DataStepsItem } from './getApiGameByGid200DataStepsItem';

export type GetApiGameByGid200Data = {
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  gid: string;
  players: GetApiGameByGid200DataPlayers;
  status: 'playing' | 'finished';
  steps: GetApiGameByGid200DataStepsItem[];
};
