/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiGame200DataItemPlayers } from './getApiGame200DataItemPlayers';
import type { GetApiGame200DataItemStepsItem } from './getApiGame200DataItemStepsItem';

export type GetApiGame200DataItem = {
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  gid: string;
  players: GetApiGame200DataItemPlayers;
  status: 'playing' | 'finished';
  steps: GetApiGame200DataItemStepsItem[];
};
