/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiGame200DataItem } from './getApiGame200DataItem';

export type GetApiGame200 = {
  data: GetApiGame200DataItem[];
};
