/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiGameByGid200Data } from './getApiGameByGid200Data';

export type GetApiGameByGid200 = {
  data: GetApiGameByGid200Data;
};
