/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiUserByUid200Data } from './getApiUserByUid200Data';

export type GetApiUserByUid200 = {
  data: GetApiUserByUid200Data;
};
