/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */

export * from './errorResponse';
export * from './getApiGame200';
export * from './getApiGame200DataItem';
export * from './getApiGame200DataItemPlayers';
export * from './getApiGame200DataItemStepsItem';
export * from './getApiGameByGid200';
export * from './getApiGameByGid200Data';
export * from './getApiGameByGid200DataPlayers';
export * from './getApiGameByGid200DataStepsItem';
export * from './getApiGameParams';
export * from './getApiUserByUid200';
export * from './getApiUserByUid200Data';
export * from './getApiUserByUid200DataHistoryItem';
export * from './getApiUserByUid200DataHistoryItemPlayers';
export * from './getApiUserByUid200DataHistoryItemStepsItem';
export * from './patchApiGameByGidBody';
export * from './patchApiGameByGidBodyStepsItem';
export * from './patchApiUserByUid200';
export * from './patchApiUserByUid200Data';
export * from './patchApiUserByUid200DataHistoryItem';
export * from './patchApiUserByUid200DataHistoryItemPlayers';
export * from './patchApiUserByUid200DataHistoryItemStepsItem';
export * from './patchApiUserByUidBody';
export * from './patchApiUserByUidBodyHistoryItem';
export * from './patchApiUserByUidBodyHistoryItemPlayers';
export * from './patchApiUserByUidBodyHistoryItemStepsItem';
export * from './postApiGame200';
export * from './postApiGameBody';
export * from './postApiGameBodyPlayers';
export * from './postApiUserBody';
export * from './webSocketByUidParams';
