/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { PatchApiUserByUid200Data } from './patchApiUserByUid200Data';

export type PatchApiUserByUid200 = {
  data: PatchApiUserByUid200Data;
};
