/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */

export type PatchApiGameByGidBodyStepsItem = {
  type: 'reveal';
  pid: string;
} | {
  type: 'move';
  pid: string;
  /** @minItems 2 */
  to: unknown[];
} | {
  type: 'capture';
  pid: string;
  targetPid: string;
  /** @minItems 2 */
  to: unknown[];
};
