/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { PatchApiUserByUid200DataHistoryItemPlayers } from './patchApiUserByUid200DataHistoryItemPlayers';
import type { PatchApiUserByUid200DataHistoryItemStepsItem } from './patchApiUserByUid200DataHistoryItemStepsItem';

export type PatchApiUserByUid200DataHistoryItem = {
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  gid: string;
  players: PatchApiUserByUid200DataHistoryItemPlayers;
  status: 'playing' | 'finished';
  steps: PatchApiUserByUid200DataHistoryItemStepsItem[];
};
