/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { PatchApiUserByUid200DataHistoryItem } from './patchApiUserByUid200DataHistoryItem';

export type PatchApiUserByUid200Data = {
  /**
     * @minLength 2
     * @pattern ^[a-zA-Z][a-zA-Z0-9_-]+$
     */
  uid: string;
  status: 'playing' | 'online' | 'offline';
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  current_gid?: string;
  history: PatchApiUserByUid200DataHistoryItem[];
};
