/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { PatchApiUserByUidBodyHistoryItemPlayers } from './patchApiUserByUidBodyHistoryItemPlayers';
import type { PatchApiUserByUidBodyHistoryItemStepsItem } from './patchApiUserByUidBodyHistoryItemStepsItem';

export type PatchApiUserByUidBodyHistoryItem = {
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  gid: string;
  players: PatchApiUserByUidBodyHistoryItemPlayers;
  status: 'playing' | 'finished';
  steps: PatchApiUserByUidBodyHistoryItemStepsItem[];
};
