/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { PatchApiUserByUidBodyHistoryItem } from './patchApiUserByUidBodyHistoryItem';

export type PatchApiUserByUidBody = {
  status: 'playing' | 'online' | 'offline';
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  current_gid?: string;
  history: PatchApiUserByUidBodyHistoryItem[];
};
