/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import type { PatchApiGameByGidBodyStepsItem } from './patchApiGameByGidBodyStepsItem';

export type PatchApiGameByGidBody = {
  status: 'playing' | 'finished';
  steps: PatchApiGameByGidBodyStepsItem[];
};
