/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */

export type PostApiUserBody = {
  /**
     * @minLength 2
     * @pattern ^[a-zA-Z][a-zA-Z0-9_-]+$
     */
  uid: string;
};
