/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */

export type PostApiGame200 = {
  /**
     * @minLength 10
     * @maxLength 10
     * @pattern ^[\w-]+$
     */
  data: string;
};
