/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GetApiGame200,
  GetApiGameByGid200,
  PostApiGame200
} from '../model';


export const getGetApiGameByGidResponseMock = (overrideResponse: Partial<Extract<GetApiGameByGid200, object>> = {}): GetApiGameByGid200 => ({data: {gid: faker.helpers.fromRegExp("^[\\w-]+$"), players: {Red: faker.helpers.fromRegExp("^[a-zA-Z][a-zA-Z0-9_-]+$"), Black: faker.helpers.fromRegExp("^[a-zA-Z][a-zA-Z0-9_-]+$")}, status: faker.helpers.arrayElement([]), steps: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([{type: {}, pid: faker.string.alpha({length: {min: 10, max: 20}})},{type: {}, pid: faker.string.alpha({length: {min: 10, max: 20}}), to: Array.from({ length: faker.number.int({min: 2, max: 10}) }, (_, i) => i + 1).map(() => ({}))},{type: {}, pid: faker.string.alpha({length: {min: 10, max: 20}}), targetPid: faker.string.alpha({length: {min: 10, max: 20}}), to: Array.from({ length: faker.number.int({min: 2, max: 10}) }, (_, i) => i + 1).map(() => ({}))},])))}, ...overrideResponse})

export const getGetApiGameResponseMock = (overrideResponse: Partial<Extract<GetApiGame200, object>> = {}): GetApiGame200 => ({data: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({gid: faker.helpers.fromRegExp("^[\\w-]+$"), players: {Red: faker.helpers.fromRegExp("^[a-zA-Z][a-zA-Z0-9_-]+$"), Black: faker.helpers.fromRegExp("^[a-zA-Z][a-zA-Z0-9_-]+$")}, status: faker.helpers.arrayElement([]), steps: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([{type: {}, pid: faker.string.alpha({length: {min: 10, max: 20}})},{type: {}, pid: faker.string.alpha({length: {min: 10, max: 20}}), to: Array.from({ length: faker.number.int({min: 2, max: 10}) }, (_, i) => i + 1).map(() => ({}))},{type: {}, pid: faker.string.alpha({length: {min: 10, max: 20}}), targetPid: faker.string.alpha({length: {min: 10, max: 20}}), to: Array.from({ length: faker.number.int({min: 2, max: 10}) }, (_, i) => i + 1).map(() => ({}))},])))})), ...overrideResponse})

export const getPostApiGameResponseMock = (overrideResponse: Partial<Extract<PostApiGame200, object>> = {}): PostApiGame200 => ({data: faker.helpers.fromRegExp("^[\\w-]+$"), ...overrideResponse})


export const getGetApiGameByGidMockHandler = (overrideResponse?: GetApiGameByGid200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiGameByGid200> | GetApiGameByGid200), options?: RequestHandlerOptions) => {
  return http.get('*/api/game/:gid', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiGameByGidResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPatchApiGameByGidMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/api/game/:gid', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetApiGameMockHandler = (overrideResponse?: GetApiGame200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetApiGame200> | GetApiGame200), options?: RequestHandlerOptions) => {
  return http.get('*/api/game', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiGameResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiGameMockHandler = (overrideResponse?: PostApiGame200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostApiGame200> | PostApiGame200), options?: RequestHandlerOptions) => {
  return http.post('*/api/game', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiGameResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGameMock = () => [
  getGetApiGameByGidMockHandler(),
  getPatchApiGameByGidMockHandler(),
  getGetApiGameMockHandler(),
  getPostApiGameMockHandler()
]
