/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorResponse,
  GetApiGame200,
  GetApiGameByGid200,
  GetApiGameParams,
  PatchApiGameByGidBody,
  PostApiGame200,
  PostApiGameBody
} from '../model';



  type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get game information
 */
export const getGetApiGameByGidUrl = (gid: string,) => {




  return `/api/game/${gid}`
}

export const getApiGameByGid = async (gid: string, options?: RequestInit): Promise<GetApiGameByGid200> => {

  const res = await fetch(getGetApiGameByGidUrl(gid),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetApiGameByGid200 = body ? JSON.parse(body) : {}
  return data
}




export const getGetApiGameByGidKey = (gid: string,) => [`/api/game/${gid}`] as const;

export type GetApiGameByGidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGameByGid>>>

export const useGetApiGameByGid = <TError = Promise<ErrorResponse>>(
  gid: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiGameByGid>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(gid)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiGameByGidKey(gid) : null);
  const swrFn = () => getApiGameByGid(gid, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Update the gaming status
 */
export const getPatchApiGameByGidUrl = (gid: string,) => {




  return `/api/game/${gid}`
}

export const patchApiGameByGid = async (gid: string,
    patchApiGameByGidBody: PatchApiGameByGidBody, options?: RequestInit): Promise<void> => {

  const res = await fetch(getPatchApiGameByGidUrl(gid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchApiGameByGidBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getPatchApiGameByGidMutationFetcher = (gid: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: PatchApiGameByGidBody }) => {
    return patchApiGameByGid(gid, arg, options);
  }
}
export const getPatchApiGameByGidMutationKey = (gid: string,) => [`/api/game/${gid}`] as const;

export type PatchApiGameByGidMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiGameByGid>>>

export const usePatchApiGameByGid = <TError = Promise<void | ErrorResponse>>(
  gid: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchApiGameByGid>>, TError, Key, PatchApiGameByGidBody, Awaited<ReturnType<typeof patchApiGameByGid>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchApiGameByGidMutationKey(gid);
  const swrFn = getPatchApiGameByGidMutationFetcher(gid, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get user's game history
 */
export const getGetApiGameUrl = (params: GetApiGameParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/game?${stringifiedParams}` : `/api/game`
}

export const getApiGame = async (params: GetApiGameParams, options?: RequestInit): Promise<GetApiGame200> => {

  const res = await fetch(getGetApiGameUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetApiGame200 = body ? JSON.parse(body) : {}
  return data
}




export const getGetApiGameKey = (params: GetApiGameParams,) => [`/api/game`, ...(params ? [params]: [])] as const;

export type GetApiGameQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGame>>>

export const useGetApiGame = <TError = Promise<ErrorResponse>>(
  params: GetApiGameParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiGame>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiGameKey(params) : null);
  const swrFn = () => getApiGame(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Create a new game
 */
export const getPostApiGameUrl = () => {




  return `/api/game`
}

export const postApiGame = async (postApiGameBody: PostApiGameBody, options?: RequestInit): Promise<PostApiGame200> => {

  const res = await fetch(getPostApiGameUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiGameBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PostApiGame200 = body ? JSON.parse(body) : {}
  return data
}




export const getPostApiGameMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: PostApiGameBody }) => {
    return postApiGame(arg, options);
  }
}
export const getPostApiGameMutationKey = () => [`/api/game`] as const;

export type PostApiGameMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGame>>>

export const usePostApiGame = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiGame>>, TError, Key, PostApiGameBody, Awaited<ReturnType<typeof postApiGame>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiGameMutationKey();
  const swrFn = getPostApiGameMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
