/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoRouteImport } from './routes/go'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as signSignupRouteImport } from './routes/(sign)/signup'
import { Route as signSigninRouteImport } from './routes/(sign)/signin'

const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const signSignupRoute = signSignupRouteImport.update({
  id: '/(sign)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const signSigninRoute = signSigninRouteImport.update({
  id: '/(sign)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/go': typeof GoRoute
  '/signin': typeof signSigninRoute
  '/signup': typeof signSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/go': typeof GoRoute
  '/signin': typeof signSigninRoute
  '/signup': typeof signSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/go': typeof GoRoute
  '/(sign)/signin': typeof signSigninRoute
  '/(sign)/signup': typeof signSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/go' | '/signin' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/go' | '/signin' | '/signup'
  id: '__root__' | '/' | '/about' | '/go' | '/(sign)/signin' | '/(sign)/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GoRoute: typeof GoRoute
  signSigninRoute: typeof signSigninRoute
  signSignupRoute: typeof signSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)/signup': {
      id: '/(sign)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof signSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)/signin': {
      id: '/(sign)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof signSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GoRoute: GoRoute,
  signSigninRoute: signSigninRoute,
  signSignupRoute: signSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
