/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Hidess API
 * Server API
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  WebSocketByUidParams
} from '../model';



  type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * WebSocket connected when UID login
 */
export const getWebSocketByUidUrl = (params: WebSocketByUidParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/ws?${stringifiedParams}` : `/ws`
}

export const webSocketByUid = async (params: WebSocketByUidParams, options?: RequestInit): Promise<unknown> => {

  const res = await fetch(getWebSocketByUidUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: unknown = body ? JSON.parse(body) : {}
  return data
}




export const getWebSocketByUidKey = (params: WebSocketByUidParams,) => [`/ws`, ...(params ? [params]: [])] as const;

export type WebSocketByUidQueryResult = NonNullable<Awaited<ReturnType<typeof webSocketByUid>>>

export const useWebSocketByUid = <TError = Promise<void>>(
  params: WebSocketByUidParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof webSocketByUid>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getWebSocketByUidKey(params) : null);
  const swrFn = () => webSocketByUid(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
